name: Shuffle Data
on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  get-verse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get random verse
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: node .

      - name: Add to git repo
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "jaykukadiya99"
          git config --global user.email "jaykukadiya99@gmail.com"
          git commit -m "[Automated] Data Shuffled!"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}